import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import React from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = React.PropsWithChildren<{}>;

export default function RootLayout({ children }: Props) {
  return (
    <html lang="en">
      <head>
        {/* <script src="https://telegram.org/js/telegram-web-app.js"></script> */}
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
