export enum BREAKPOINTS {
  SMALL = "sm",
  MEDIUM = "md",
  LARGE = "lg",
  XLARGE = "xl",
  X2LARGE = "2xl",
}

export const BREAKPOINT_VALUES: Record<BREAKPOINTS, number> = {
  [BREAKPOINTS.SMALL]: 640,
  [BREAKPOINTS.MEDIUM]: 768,
  [BREAKPOINTS.LARGE]: 1024,
  [BREAKPOINTS.XLARGE]: 1280,
  [BREAKPOINTS.X2LARGE]: 1536,
};

export const CONTAINER_SIZE: Record<BREAKPOINTS, number> = {
  [BREAKPOINTS.SMALL]: 450,
  [BREAKPOINTS.MEDIUM]: 524,
  [BREAKPOINTS.LARGE]: 700,
  [BREAKPOINTS.XLARGE]: 700,
  [BREAKPOINTS.X2LARGE]: 700,
};
